version: "3.9"

x-networks: &networks
  networks:
    - dockernet

x-environment: &environment
  env_file:
    - .env

services:
  app:
    container_name: app
    image: patrick204nqh/ci-express-app:latest
    build:
      context: .
      dockerfile: docker/node/dockerfile.dev
    tty: true
    working_dir: /var/www
    volumes:
      - $PWD/:/var/www
      - nodemodules:/var/www/node_modules
    ports:
      - '8080:8080'
    command: >
      sh -c "npm install && node server.js"
    <<: *environment
    <<: *networks

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/dockerfile.dev
  #   image: patrick204nqh/ci-express-nginx:latest
  #   <<: *networks

networks:
  dockernet:
    driver: bridge

volumes:
  nodemodules:
