version: "3.9"

services:
  express:
    image: patrick204nqh/ci-express-app:latest
    build: .
    container_name: ci-express
    entrypoint: ["yarn", "start"]
    ports:
      - 3000:3000
    volumes:
      - $PWD:/var/www/app
