name: Build docker images

on:
  push:
    branches: [ master ]
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ develop ]

env:
  DOCKER_NAME: patrick204nqh
  REPO_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: butlerlogic/action-autotag@stable
        if: github.event_name != 'pull_request'
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push Backend
        id: build-and-push-backend
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_NAME }}/${{ env.REPO_NAME }}-backend:latest
          labels: 'Backend'

      - name: Build and push Frontend
        id: build-and-push-frontend
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_NAME }}/${{ env.REPO_NAME }}-frontend:latest
          labels: 'Frontend'
