name: Build docker images

on:
  push:
    branches: [ master ]
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ develop ]

env:
  REPO_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: butlerlogic/action-autotag@stable
        if: github.event_name != 'pull_request'
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        id: build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: docker.io/patrick204nqh/${{ env.REPO_NAME }}-backend:latest

      - name: Build and push Frontend
        id: build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: docker.io/patrick204nqh/${{ env.REPO_NAME }}-frontend:latest
